const x= 10;

try{
    y= 10;
} catch(err){
    console.log(`Erro ${err}`)
}

console.log(' continue programar.....')